name: myfirst-workflow
#to get a triggeron every push in this repo in every branch
on: push

jobs:
  firstJob:
   name: job1
   runs-on: windows-latest
   steps:
    - name: Running Single command in firstJob
      run: echo "Hi this is my first job"
    - name: Checking Runner info
      run: get-computerinfo
      shell: push
    - name: calling sleep
      run: sleep 20
  secondJob:
   name: Job2
   runs-on: ubuntu-latest
   steps:
    - name: Checking the Hostname for runner
      run: hostname
    - name: running multiple name
      run: 
       echo "Hi i am sudhanshi"
       echo "current time is 10pm"
       sleep 20
  thirdJob:
   name: Job3
   needs: firstJob
   runs-on: ubuntu-latest
   steps:
    - name: Job with single dependency
      run: sleep 10
  fourthJob:
   name: Job4
   needs: [firstJob, secondJob, thirdJob]
   runs-on: ubuntu-latest
   steps:
    - name: Job with multiple dependencies
      run: sleep 10
