name: myfirst-workflow
#to get a triggeron every push in this repo in every branch
on: push

jobs:
  firstJob:
     name: job1
     runs-on: ubuntu-latest
     steps:
      - name: Running Single command in firstJob
       run: echo "Hi this is my first job"
      - name: Checking OS Release for Github Hosted Runner
       run: cat /etc/os-release
      
